language: python
python: 3.7
jobs:
  include:
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      env: PATH=/c/Python37-32:/c/Python37-32/Scripts:$PATH
install:
  - pip install pipenv
  - pipenv sync
script:
  - pipenv run pyinstaller main.py