language: python
python: 3.7
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
jobs:
  include:
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      env: PATH=/c/Python37-32:/c/Python37-32/Scripts:$PATH
install:
  - pip install pipenv
  - pipenv --three
  - pipenv install git+https://github.com/ENDERZOMBI102/BEE-manipulator.git
  - pipenv install
script:
  - pipenv run pyinstaller main.py