# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build BM

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      # cache!
    - name: Cache
      id: cache
      uses: actions/cache@v2.1.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          C:\ProgramData\chocolatey\lib\upx
          C:\ProgramData\chocolatey\lib\7zip.portable
        # An explicit key for restoring and saving the cache
        key: progs
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: progs
    # install
    - name: install 7zip and UPX
      # install the progs only if the cache doesn't exist
      if: steps.cache.outputs.cache-hit != 'true'
      run: choco install 7zip.portable upx
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel --no-input
        pip install -r requirements.txt --no-input
        # pip install git+https://github.com/htgoebel/pyinstaller/tree/issue-4158-pydantic --no-input
        pip install pyinstaller --no-input
    # build
    - name: Build bm
      run: |
        pyinstaller src/BEEManipulator_release.spec --noconfirm --upx-dir="C:\ProgramData\chocolatey\lib\upx\tools\upx-3.96-win64"
        C:\ProgramData\chocolatey\lib\7zip.portable\tools\7z-extra\7za.exe a -r BEEManipulator ./dist/"BEE Manipulator"/*
    # upload a release!
    - name: Create GitHub release
      run: |
        echo ${{ secrets.GIHUB_TOKEN }}
      
